### ISSUE TITLE
CSP Meta not being recognised?

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#23] opened 2021-02-02 14:21 UTC
### Describe the bug

Adding in a CSP on a client site now that Sherlock is highlighting it. However sherlock isn't picking up the meta tag:

![image](https://user-images.githubusercontent.com/7523595/106613011-a2a6b700-6561-11eb-9679-806165f91173.png)

The CSP is definitely working. You can see it in the meta here:

![image](https://user-images.githubusercontent.com/7523595/106613043-aa665b80-6561-11eb-8432-236f256e5baa.png)

And to confirm 100% it working I'm (correctly) getting an CSP error as I've not added bugsnag's domain to the CSP:

![image](https://user-images.githubusercontent.com/7523595/106613056-ae927900-6561-11eb-80c4-6083bf9357ac.png)

### Versions
- Plugin version: 3.1.0
- Craft version:Craft Pro 3.6.2
- Browser For Screenshots: Chrome 88

**Comment by bencroker** [comment] 2021-02-02 17:28
That was being caused by the line breaks in the meta tag. Fixed in https://github.com/putyourlightson/craft-sherlock/commit/a167529fb2c1e771b69de2186ebb92910310d9eb for the next release.

**Closed as completed by bencroker** 2021-02-02 17:28 UTC
Labels: bug

**Comment by bencroker** [comment] 2021-02-03 10:48
Released in version 3.1.1.
